### ISSUE TITLE
games_mp.log gets overwritten at every container (re)start

### ISSUE THREAD

**Issue by Freekers** [qdm12/cod4-docker#12]
The games_mp.log gets overwritten/cleaned every time the container (re)starts. This is annoying, as I use the .log to parse statistics. 

`g_logsync` is set to `3` in my server.conf, which should append the logfile every time the server is restarted:

> 1. - buffered means that the logs are not written to disk continuously, they are temporarily buffered in memory and written to disk later.
> 2. - continuous means that logs are written to disk when the event takes place. After a server restart a new log will be created. You will lose old logs after a restart/crash.
> 3. - append does the same as continuous but after a server restart the new loglines are appended to the previous log.

How can I prevent the logfile from being overwritten/cleaned  every time the container (re)starts? 

Thanks!

**Comment by qdm12** [comment]
Where is you log stored in the container? What image tag are you using? Maybe share your Docker volumes configuration.

**Comment by Freekers** [comment]
- Logs are stored in the main folder.
- I'm using my own image tag, but it is based on your image. I simply swapped the 18x binaries for 1.7a.
- My Docker volumes are as follows:
```   
volumes:
     - /opt/cod4/stock/main:/home/user/cod4/main
     - /opt/cod4/stock/zone:/home/user/cod4/zone:ro
     - /opt/cod4/stock/plugins:/home/user/cod4/plugins:ro
     - /opt/cod4/stock/mods:/home/user/cod4/mods
     - /opt/cod4/stock/usermaps:/home/user/cod4/usermaps:ro
```

**Comment by qdm12** [comment]
It's likely just a cod4x configuration. I don't really use log files for my server (private only) so I might not be the one to know how. Maybe try asking on the cod4x.me forums?

Or does it work (append to log file) without a container?

**Comment by Freekers** [comment]
My bad, I had an error in one of my cronjobs that accidentally overwrited the logfiles every night...Whoopsies!

**Comment by qdm12** [comment]
Cool, no problem; it happens to all of us :wink:
