### ISSUE TITLE
Some error in the docker logs

### ISSUE THREAD

**Issue by samatkiss** [qdm12/cod4-docker#4]
Hi!

I see this errors in the docker logs:
Failed to open serverstatus.xml
Couldn't write q3config_server.cfg
1Error: Waited 227 msec for missing asset "codescripts/delete.gsx"
^3Warning: WARNING: Couldn't open logfile: main/games_mp.log

The permissions are 777 on all direcetories.

Please help.
Thanks

**Comment by qdm12** [comment]
Hi there,

Indeed these are meant to be and I believe they are related to the image being based on Scratch. I'll do another Docker image tag based on Alpine so that these errors don't show up anymore. But do these cause any real problem? 

Thanks!

**Comment by samatkiss** [comment]
Hi!

Thank you for the quick reply!
These dont cause any problem (or i havent noticed yet) in the running.
Im not a cod4 server master so i dont know exactl what these things used for.
But!
I would like to setup the logging. But this doesnt work. I set the logging parameters in the log file, but it doesnt find the games_mp.log file but i created it in the main folder.
I tried with “game_mp.log” and “main/game_mp.log” but the warning is the same and the file is empty.
Do you have idea how i solve this?

**Comment by samatkiss** [comment]
Hi!

Could you help?
Can i remove this error: 
Failed to open serverstatus.xml
It is generated in every minute.

Thanks

**Comment by qdm12** [comment]
Hi @samatkiss,

I have pushed something that at least fixes the

```
Failed to open serverstatus.xml
Couldn't write q3config_server.cfg
```

warnings, although your log file might still not work.

Can you please try

```sh
docker pull qmcgaw/cod4-docker
```

And then restart your container to see if it works now? Thanks!
