### ISSUE TITLE
Logging doesnt work

### ISSUE THREAD

**Issue by samatkiss** [qdm12/cod4-docker#5]
Hi!

Could you repair the cod4 logging?

Thanks
Tamás

**Comment by qdm12** [comment]
Hi there,

1. Could you share how you create the log from your COD4 server configuration?
1. Do you have any error messages in the docker logs
1. Do you bind mount (with `-v /path:/path` or in `volumes` in docker-compose.yml) the log file?

Thanks

**Comment by samatkiss** [comment]
1. With the command `+set dedicated 2+set sv_cheats 0+set sv_punkbuster 0+set sv_maxclients 64+set ui_maxclients 64+set fs_game mods/pml220+exec server.cfg+map_rotate+set rcon_password xxxxxxx +set g_logsync 2+ set logfile 1+ set sv_punkbuster 1+ set g_log main/games_mp.log+ set sv_statusfile serverstatus.xml`
2. No
3. The log file is in main so is bind mounted in a way

**Comment by qdm12** [comment]
Indeed it does not work. I am trying to access [cod4x.me](https://cod4x.me) website to understand why but it is offline now.

For now, it does not create any `game_mp.log` file by itself nor write to an existing one (in `main` or `mods/pm1220`. What you can do for now is simply store the logs from Docker although it's not perfect.

I will check again the next few days to see if the website comes back online.

**Comment by samatkiss** [comment]
Hi!

Thank you very much!

Good night

Tamas

Quentin McGaw <notifications@github.com> (időpont: 2019. ápr. 29., H,
22:52) ezt írta:

**Comment by qdm12** [comment]
Hi @samatkiss ,

I posted a [question on Cod4x forums](https://cod4x.me/index.php?/forums/topic/3426-where-does-logs-go/), I will let you know once I find out why it does not work.

Thanks !

**Comment by samatkiss** [comment]
Thank you!

Quentin McGaw <notifications@github.com> (időpont: 2019. máj. 8., Sze,
21:54) ezt írta:

**Comment by Koalatyyy** [comment]
As I commented on the cod4x post, try the ~/.callofduty4/main folder (note the "." at the beginning) some of my logs appear there for my personal servers.

**Comment by qdm12** [comment]
Hi @Koajakins thanks for the help ! Is there any way to setup the directory path instead of `~/.callofduty4` ?

@samatkiss ~I have added to the documentation how to do it.~ [**See last answer below!**](https://github.com/qdm12/cod4-docker/issues/5#issuecomment-490825239)

1. Create a directory

    ```sh
    mkdir logs
    chown 1000 logs
    chmod 700 logs
    ```

1. Bind mount the volume with `-v $(pwd)/logs:/home/user/.callofduty4` or, in docker-compose.yml:

    ```yml
    volumes:
        - ./logs:/home/user/.callofduty4
    ```

**Comment by Koalatyyy** [comment]
+set fs_homepath <path> in the run script would most likely work fine.
+set fs_homepath . would then place it into "main" I believe, though I haven't messed with it in a while.

**Comment by Koalatyyy** [comment]
https://github.com/qdm12/cod4-docker/blob/55ed1e5ae4cc15e2655383d5178f988a29254b07/Dockerfile#L45

**Comment by qdm12** [comment]
Hi @Koajakins thanks for the tip !!

@samatkiss no need to do anything in the end, the logs will now be in `mods/yourmod` or in `main` if you run the server without mods. Happy gaming !
