### ISSUE TITLE
Permissions zone and usermaps folder

### ISSUE THREAD

**Issue by Freekers** [qdm12/cod4-docker#7]
Thank you for creating this Docker image!

In the README it says that the `zone` and `usermaps` folder should have chmod 400 permissions, but with those permissions the Docker container wouldn't start for me. Changing the permissions chmod 700, just like the `main` and `mods` folder, fixed the issue for me.

**Comment by qdm12** [comment]
Uh ok good to know, although it should only need read access. I'll update the readme. I guess who cares if it accidentally deletes a map :smile: Thanks for reporting anyway
